name:                apron-bindings
version:             0.1.0.0
github:              "mlfbrown/apron-bindings"
license:             GPL
author:              "Fraser Brown and Deian Stefan"
maintainer:          "mlfbrown@cs.ucsd.edu"
copyright:           "2020 Fraser Brown and Deian Stefan"

build-type: Configure
extra-source-files:
- README.md
- autoconf.ac
- configure

# Metadata used when publishing your package
synopsis:            Haskell bindings for the Apron Numerical Abstract Domain Library
category:            Static-analysis

description:         Please see the README on GitHub at <https://github.com/mlfbrown/apron-bindings#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  build-tools: c2hs
  extra-libraries:  apron

executables:
  apron-bindings-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - apron-bindings

tests:
  apron-bindings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - apron-bindings
    - tasty
    - tasty-hunit
